#!/bin/sh
# Rules for firewall
WAN_IFACE=eth0

case "$1" in
	start)
	  echo "Starting FW..."
	  echo 1 > /proc/sys/net/ipv4/ip_forward
	  iptables -t nat -F
	  iptables -F
	  iptables -P INPUT DROP
	  iptables -P OUTPUT DROP
	  iptables -P FORWARD DROP
	  ########## Reglas para permitir acceso ssh ##############
	  iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
	  iptables -A OUTPUT -p tcp --sport 22 -m state --state ESTABLISHED,RELATED -j ACCEPT
	  iptables -A OUTPUT -o $WAN_IFACE -j ACCEPT
	  iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

	  iptables -A FORWARD -p icmp -j ACCEPT
	  iptables -A FORWARD -i dmz -o lan -j DROP
	  iptables -A FORWARD -p udp --dport 53 -j ACCEPT
	  iptables -A FORWARD -p tcp --dport 53 -j ACCEPT
	  iptables -A FORWARD -p tcp --dport 22 -j ACCEPT
	  iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
	  iptables -A FORWARD -p tcp --dport 8080 -j ACCEPT
	  iptables -A FORWARD -p tcp --dport 443 -j ACCEPT
	  iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
	  iptables -A FORWARD -i dmz -o $WAN_IFACE -j DROP

	  iptables -A FORWARD -o $WAN_IFACE -j ACCEPT
          iptables -t nat -A POSTROUTING -o $WAN_IFACE -j MASQUERADE
		;;

	stop)
	  echo "Stopping FW..."
	  iptables -t nat -F POSTROUTING
	  iptables -F
	  iptables -P INPUT ACCEPT
	  iptables -P OUTPUT ACCEPT
	  iptables -P FORWARD ACCEPT

		;;

	restart|reload)
	  	$0 stop
	  	$0 start
		;;

	*)
	echo "Usage: $0 {start|stop|restart|reload|}"
	exit 1
		;;
		
esac
exit 0
